apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimic-iv-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimic-iv-pipeline
  template:
    metadata:
      labels:
        app: mimic-iv-pipeline
    spec:
      containers:
      - name: mimic-iv-pipeline
        image: mimic-iv-pipeline:latest
        ports:
        - containerPort: 8888
        env:
        - name: MIMIC_IV_DATA_PATH
          value: /data
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
