apiVersion: v1
kind: Service
metadata:
  name: mimic-iv-pipeline
spec:
  selector:
    app: mimic-iv-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 30009
  type: NodePort
